In [1]:
import numpy as np

from astropy.io import fits
from astropy.table import Table

from astroML.density_estimation import XDGMM

## Load Data

In [2]:
data_ic = Table.read("data/outputs/ic348_apogee.csv")
data_ngc = Table.read("data/outputs/ngc1333_apogee.csv")

## Run Deconvolution

#### IC 348
$\textit{set up array}$

In [3]:
X_ic = np.vstack([data_ic['RV']]).T
Xerr_ic = np.zeros(X_ic.shape + X_ic.shape[-1:])

for i in range(0,data_ic['e_RV'].shape[0]):
    np.fill_diagonal(Xerr_ic[i],[data_ic['e_RV'][i]**2])

$\textit{run deconvolution}$

In [4]:
clf_ic = XDGMM(n_components = 2)
clf_ic.fit(X_ic, Xerr_ic)

mu_ic = clf_ic.mu
V_ic = clf_ic.V
alpha_ic = clf_ic.alpha

/n/home07/dkhimey/.conda/envs/standard/lib/python3.7/site-packages/sklearn/mixture/_base.py:269: ConvergenceWarning: Initialization 1 did not converge. Try different init parameters, or increase max_iter, tol or check for degenerate data.
  % (init + 1), ConvergenceWarning)


$\textit{gaussian results}$

In [5]:
print(f"Amplitudes:\n{alpha_ic}")

Amplitudes:
[0.09360448 0.90639552]


In [6]:
# select main cluster
amp_mask_ic = alpha_ic > .5

mean_ic = mu_ic[amp_mask_ic]
sigma_ic = np.sqrt(V_ic[amp_mask_ic])

#### NGC 1333
$\textit{set up array}$

In [7]:
X_ngc = np.vstack([data_ngc['RV']]).T
Xerr_ngc = np.zeros(X_ngc.shape + X_ngc.shape[-1:])

for i in range(0,data_ngc['e_RV'].shape[0]):
    np.fill_diagonal(Xerr_ngc[i],[data_ngc['e_RV'][i]**2])

$\textit{run deconvolution}$

In [8]:
clf_ngc = XDGMM(n_components = 2)
clf_ngc.fit(X_ngc, Xerr_ngc)

mu_ngc = clf_ngc.mu
V_ngc = clf_ngc.V
alpha_ngc = clf_ngc.alpha

/n/home07/dkhimey/.conda/envs/standard/lib/python3.7/site-packages/sklearn/mixture/_base.py:269: ConvergenceWarning: Initialization 1 did not converge. Try different init parameters, or increase max_iter, tol or check for degenerate data.
  % (init + 1), ConvergenceWarning)


$\textit{gaussian results}$

In [9]:
print(f"Amplitudes:\n{alpha_ngc}")

Amplitudes:
[0.97916654 0.02083346]


In [10]:
# select main cluster
amp_mask_ngc = alpha_ngc > .5

mean_ngc = mu_ngc[amp_mask_ngc]
sigma_ngc = np.sqrt(V_ngc[amp_mask_ngc])

## Summary 

In [11]:
print("IC 348 Dispersion")
print(f"Rvel mean    : {mean_ic}")
print(f"Rvel sigma   : {sigma_ic}")

print("NGC 1333 Dispersion")
print(f"Rvel mean    : {mean_ngc}")
print(f"Rvel sigma   : {sigma_ngc}")

IC 348 Dispersion
Rvel mean    : [[15.14131764]]
Rvel sigma   : [[[0.67956875]]]
NGC 1333 Dispersion
Rvel mean    : [[14.28832179]]
Rvel sigma   : [[[0.99079429]]]


Cottaar et al (2015), sigma IC 348 : 0.72 ± 0.07 km/s

Foster et al (2015), sigma NGC 1333 : 0.92 ± 0.12 km/s